### ISSUE TITLE
new social media cards

### ISSUE THREAD

**Issue by yangwao** [kodadot/presskit#5]
we will need cards for various occasions to engage with the audience, @anettrolikova will help us
- [x] carbonless
- [x] rmrk/mint
- [x] discord welcome banner
- [x] rmrk/gallery
- [x] sustainability

**Comment by anettrolikova** [comment]
Just added #6 PR with Mint NFT banner

**Comment by anettrolikova** [comment]
Added another files to the PR with Discord, Sustainability and Gallery banners

**Comment by anettrolikova** [comment]
@yangwao you can close this issue as all the banners are uploaded in Presskit

**Comment by yangwao** [comment]
Closed in #6
